CREATE TABLE IF NOT EXISTS fact_store_spu_price_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  batch_id CHAR(36) NOT NULL COMMENT '采集批次 ID',
  snapshot_hour DATETIME NOT NULL COMMENT 'Asia/Shanghai 采集时间，精确到小时',
  channel_code VARCHAR(32) NOT NULL COMMENT '渠道编码',
  store_code VARCHAR(128) NOT NULL COMMENT '门店稳定编码',
  store_name VARCHAR(255) NOT NULL COMMENT '门店名称',
  store_role VARCHAR(32) NOT NULL COMMENT 'own 或 competitor',
  category_name VARCHAR(255) DEFAULT NULL COMMENT '主类目原文',
  category_order INT DEFAULT NULL COMMENT '门店类目顺序',
  source_spu_id VARCHAR(128) NOT NULL COMMENT '平台来源 SPU ID',
  standard_spu_id VARCHAR(64) DEFAULT NULL COMMENT '标准 SPU ID',
  product_name VARCHAR(512) NOT NULL COMMENT '来源商品名称，禁止改写',
  front_display_price_amount DECIMAL(18,4) DEFAULT NULL COMMENT '前端展示价',
  user_final_price_amount DECIMAL(18,4) DEFAULT NULL COMMENT '有证据的用户到手价',
  original_price_amount DECIMAL(18,4) DEFAULT NULL COMMENT '原价或划线价',
  promotion_text VARCHAR(1024) DEFAULT NULL COMMENT '前端优惠文案',
  match_status VARCHAR(32) NOT NULL DEFAULT 'unmatched' COMMENT 'matched、unmatched 或 review',
  PRIMARY KEY (id),
  UNIQUE KEY uk_store_spu_snapshot (batch_id, store_code, source_spu_id),
  KEY idx_store_spu_category (store_code, snapshot_hour, category_order, source_spu_id),
  KEY idx_store_spu_standard (standard_spu_id, snapshot_hour),
  KEY idx_store_spu_name (product_name(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='门店 SPU 价格快照，业务列表和 SPU 回退比价使用';

CREATE TABLE IF NOT EXISTS fact_store_sku_price_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  batch_id CHAR(36) NOT NULL COMMENT '采集批次 ID',
  snapshot_hour DATETIME NOT NULL COMMENT 'Asia/Shanghai 采集时间，精确到小时',
  channel_code VARCHAR(32) NOT NULL COMMENT '渠道编码',
  store_code VARCHAR(128) NOT NULL COMMENT '门店稳定编码',
  store_name VARCHAR(255) NOT NULL COMMENT '门店名称',
  store_role VARCHAR(32) NOT NULL COMMENT 'own 或 competitor',
  category_name VARCHAR(255) DEFAULT NULL COMMENT '主类目原文',
  category_order INT DEFAULT NULL COMMENT '门店类目顺序',
  source_spu_id VARCHAR(128) NOT NULL COMMENT '平台来源 SPU ID',
  source_sku_id VARCHAR(128) NOT NULL COMMENT '平台来源 SKU ID',
  standard_spu_id VARCHAR(64) DEFAULT NULL COMMENT '标准 SPU ID',
  standard_sku_id VARCHAR(64) DEFAULT NULL COMMENT '标准 SKU ID',
  product_name VARCHAR(512) NOT NULL COMMENT '来源商品名称，禁止改写',
  spec_name VARCHAR(255) DEFAULT NULL COMMENT '来源规格名称',
  upc VARCHAR(255) DEFAULT NULL COMMENT '商品条码',
  front_display_price_amount DECIMAL(18,4) DEFAULT NULL COMMENT 'SKU 前端展示价',
  user_final_price_amount DECIMAL(18,4) DEFAULT NULL COMMENT '有证据的 SKU 到手价',
  original_price_amount DECIMAL(18,4) DEFAULT NULL COMMENT 'SKU 原价',
  promotion_text VARCHAR(1024) DEFAULT NULL COMMENT 'SKU 或 SPU 优惠文案',
  min_purchase_quantity DECIMAL(18,4) DEFAULT NULL COMMENT '起购数量',
  limit_purchase_quantity DECIMAL(18,4) DEFAULT NULL COMMENT '限购数量',
  stock_quantity DECIMAL(18,4) DEFAULT NULL COMMENT '库存或可售数量',
  sale_status VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT 'available、out_of_stock 或 unknown',
  match_status VARCHAR(32) NOT NULL DEFAULT 'unmatched' COMMENT 'matched、unmatched 或 review',
  PRIMARY KEY (id),
  UNIQUE KEY uk_store_sku_snapshot (batch_id, store_code, source_spu_id, source_sku_id),
  KEY idx_store_sku_category (store_code, snapshot_hour, category_order, source_spu_id, source_sku_id),
  KEY idx_store_sku_standard (standard_sku_id, snapshot_hour),
  KEY idx_store_sku_upc (upc, snapshot_hour),
  KEY idx_store_sku_name_spec (product_name(191), spec_name(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='门店 SKU 价格快照，SKU 优先比价使用';
